export enum SoundType {
  EAT_SNACK = 'EAT_SNACK', GAME_END = 'GAME_END', CHICKEN = 'CHICKEN', GHOST_SCARES_SNACKMAN = 'GHOST_SCARES_SNACKMAN',
  GHOST_SCARES_CHICKEN = 'GHOST_SCARES_CHICKEN', INGAME_BACKGROUND = 'INGAME_BACKGROUND', LOBBY_MUSIC = 'LOBBY_MUSIC',
  GHOST = 'GHOST'
}
